### PR TITLE
Simplify one-liner command to use tar

### PR DESCRIPTION
**Pull request by pyrech**

### CODE REVIEW

**Comment by damienalexandre** [comment]
:+1:

**Comment by joelwurtz** [comment]
```
wget -qO- https://github.com/jolicode/codintgstyle/archive/master.tar.gz | tar xvz
```

?

**Comment by pyrech** [comment]
If using, tar, we need to add the ` --strip-components=1` option to skip the `codingstyle-master`  directory and extract everything in the current directory.

But :+1: for using tar:
```shell
wget -O- https://github.com/jolicode/codingstyle/archive/master.tar.gz | tar xvz --strip-components=1
```

**Comment by pyrech** [comment]
PR updated :)

**Comment by joelwurtz** [comment]
:+1:

**Comment by damienalexandre** [comment]
:sheep:

**Pull request merged**
