### PR TITLE
Change git push default mode to current

### PR DESCRIPTION
**Pull request by pyrech**
As seen in https://git-scm.com/docs/git-config, simple mode is the default in git 2.0

### CODE REVIEW

**Comment by damienalexandre** [comment]
I'm ok with that, I almost always have the same name locally and remotely.

**Comment by pyrech** [comment]
Hmm, after some thoughts, the mode I really need is `current`, not `simple`: it allows to push a new branch without having to `git push --set-upstream origin {branch-name}`.

Any opinion about switching to `current`?

**Comment by ternel** [comment]
My config is `current`... so :+1: for me

**Comment by damienalexandre** [comment]
Ping @jolicode/jolicodeurs, what do you think about making it the default?

It looks useful to me.

**Comment by spyl94** [comment]
:+1:

**Comment by welcoMattic** [comment]
:+1: for current, I use it for a while

**Comment by franek** [comment]
go go go :+1: It is already my config ;)

**Comment by pyrech** [comment]
Updated with `current` mode :wink:

**Comment by damienalexandre** [comment]
You can merge :sheep:

**Pull request merged**
